name: OSX-CI

on: [push, pull_request]

jobs:
  build:

    runs-on: macos-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up miniconda
        uses: conda-incubator/setup-miniconda@v3.0.1
        with:
          channels: conda-forge
          python-version: ${{ matrix.python-version }}

      - name: Set up Conda environment
        shell: "bash -l {0}"
        run: >
          conda create --name "magenpy_ci" -c conda-forge -c anaconda 
          python=${{matrix.python-version}} pip wheel compilers openblas -y

      - name: Install magenpy
        shell: "bash -l {0}"
        run: |
          conda activate magenpy_ci
          python -m pip install -v -e .[test]

      - name: Run tests
        shell: "bash -l {0}"
        run: |
          conda activate magenpy_ci
          pytest -v